### ISSUE TITLE
missing SecurityLib files

### ISSUE THREAD

**Issue by madebycambiamentico** [ircmaxell/RandomLib#49]
add to lib folder, or tell users that they need that library founded in your https://github.com/ircmaxell/SecurityLib/releases.
don't know if the installer install securitylib as well, but for users which like the manual download this can be frustrating.

**Comment by nubs** [comment]
You can see the full requirements of any composer project or library by looking in the composer.json.  For example: https://github.com/ircmaxell/RandomLib/blob/master/composer.json#L20-L23.  You should definitely look into learning composer even if you aren't using it since there are so many projects that do.

**Comment by madebycambiamentico** [comment]
yes, I understand, but in the readme it's so simple to add a line stating "this project depends on xxx" since there's a sentence which describe how to install manually.

**Comment by Joohansson** [comment]
If I don't use composer, how do I add the SecurityLib properly? I get "Fatal error: Class 'SecurityLib\AbstractFactory' not found" from the Factory.php. I just want to try this library and not an PHP expert.

**Comment by madebycambiamentico** [comment]
@Joohansson go to https://github.com/ircmaxell?tab=repositories and download the needed repository.
